//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaGo.UI.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmegaGo.UI.Localization.LocalizedStrings", typeof(LocalizedStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluffy uses an n-ply alpha-beta tree to figure out the best move. This is often called the minimax algorithm. In the last layer, heuristics are used to score the board position.
        ///Fluffy will always and only pass in response to its opponent passing.
        ///You may set the depth the AI will search. Increasing the depth will increase the AI&apos;s thinking time..
        /// </summary>
        public static string AI_AlphaBetaPlayerWrapper_Description {
            get {
                return ResourceManager.GetString("AI_AlphaBetaPlayerWrapper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluffy (minimax).
        /// </summary>
        public static string AI_AlphaBetaPlayerWrapper_Name {
            get {
                return ResourceManager.GetString("AI_AlphaBetaPlayerWrapper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strongest AI program in this game, the Defeatist will resign the first time it gets the chance to. You are simply not worth its time.
        ///After you make your first move, or even before that, the AI will conclude that it&apos;s much stronger than you and just resign in order to not play a game with a foregone conclusion..
        /// </summary>
        public static string AI_DefeatistAI_Description {
            get {
                return ResourceManager.GetString("AI_DefeatistAI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeatist.
        /// </summary>
        public static string AI_DefeatistAI_Name {
            get {
                return ResourceManager.GetString("AI_DefeatistAI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuego is a well-known open-source Go-playing engine written at the University of Alberta in Canada.
        ///It uses Monte Carlo tree search to make moves. It&apos;s capable of placing stones, passing and resigning, as the situation calls for.
        ///We recommend you use this AI program for all of your games..
        /// </summary>
        public static string AI_FuegoAI_Description {
            get {
                return ResourceManager.GetString("AI_FuegoAI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuego.
        /// </summary>
        public static string AI_FuegoAI_Name {
            get {
                return ResourceManager.GetString("AI_FuegoAI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AI uses a simple heuristic to determine where to play the next move. The heuristic is based on influence and on all previous stone placements in the game history.
        ///This AI will pass only in response to its opponent passing, in which case it will always pass..
        /// </summary>
        public static string AI_HeuristicPlayerWrapper_Description {
            get {
                return ResourceManager.GetString("AI_HeuristicPlayerWrapper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Puppy (heuristic).
        /// </summary>
        public static string AI_HeuristicPlayerWrapper_Name {
            get {
                return ResourceManager.GetString("AI_HeuristicPlayerWrapper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AI will select a random position at which it can play and it will play there. It will pass as soon its opponent passes..
        /// </summary>
        public static string AI_RandomAI_Description {
            get {
                return ResourceManager.GetString("AI_RandomAI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string AI_RandomAI_Name {
            get {
                return ResourceManager.GetString("AI_RandomAI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AI plays random moves while the board is not empty.
        ///I dare you to let two Fish play against each other. The game will never end (unless you&apos;re very lucky)..
        /// </summary>
        public static string AI_RandomPlayerWrapper_Description {
            get {
                return ResourceManager.GetString("AI_RandomPlayerWrapper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fish.
        /// </summary>
        public static string AI_RandomPlayerWrapper_Name {
            get {
                return ResourceManager.GetString("AI_RandomPlayerWrapper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string AutoLanguage {
            get {
                return ResourceManager.GetString("AutoLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board border thickness.
        /// </summary>
        public static string BoardBorderThickness {
            get {
                return ResourceManager.GetString("BoardBorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board settings.
        /// </summary>
        public static string BoardSettings {
            get {
                return ResourceManager.GetString("BoardSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Size.
        /// </summary>
        public static string BoardSize {
            get {
                return ResourceManager.GetString("BoardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell size.
        /// </summary>
        public static string CellSize {
            get {
                return ResourceManager.GetString("CellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View information about the game authors and license information..
        /// </summary>
        public static string CreditsToolTip {
            get {
                return ResourceManager.GetString("CreditsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selection.
        /// </summary>
        public static string DeleteSelection {
            get {
                return ResourceManager.GetString("DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by source.
        /// </summary>
        public static string FilterBySource {
            get {
                return ResourceManager.GetString("FilterBySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game library.
        /// </summary>
        public static string GameLibrary {
            get {
                return ResourceManager.GetString("GameLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library of your past games and all your SGF files.
        /// </summary>
        public static string GameLibraryToolTip {
            get {
                return ResourceManager.GetString("GameLibraryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay.
        /// </summary>
        public static string Gameplay {
            get {
                return ResourceManager.GetString("Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the rules, documentation and other interesting information..
        /// </summary>
        public static string HelpToolTip {
            get {
                return ResourceManager.GetString("HelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, restart the game to see the language you have chosen..
        /// </summary>
        public static string LanguageChangeInfo {
            get {
                return ResourceManager.GetString("LanguageChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load folder.
        /// </summary>
        public static string LoadFolder {
            get {
                return ResourceManager.GetString("LoadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local game.
        /// </summary>
        public static string LocalGame {
            get {
                return ResourceManager.GetString("LocalGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Go against another player on the same device or against an AI..
        /// </summary>
        public static string LocalGameToolTip {
            get {
                return ResourceManager.GetString("LocalGameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Go.
        /// </summary>
        public static string OmegaGo {
            get {
                return ResourceManager.GetString("OmegaGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-line game.
        /// </summary>
        public static string OnlineGame {
            get {
                return ResourceManager.GetString("OnlineGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Go against players on the IGS or OGS online servers..
        /// </summary>
        public static string OnlineGameToolTip {
            get {
                return ResourceManager.GetString("OnlineGameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGA.
        /// </summary>
        public static string RulesetType_AGA {
            get {
                return ResourceManager.GetString("RulesetType_AGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string RulesetType_Chinese {
            get {
                return ResourceManager.GetString("RulesetType_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string RulesetType_Japanese {
            get {
                return ResourceManager.GetString("RulesetType_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language, audio, visual style and many other things..
        /// </summary>
        public static string SettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleplayer.
        /// </summary>
        public static string Singleplayer {
            get {
                return ResourceManager.GetString("Singleplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn Go, play against an AI, solve problems or gain experience completing quests..
        /// </summary>
        public static string SingleplayerToolTip {
            get {
                return ResourceManager.GetString("SingleplayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your winrate and other statistics..
        /// </summary>
        public static string StatisticsToolTip {
            get {
                return ResourceManager.GetString("StatisticsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide tips..
        /// </summary>
        public static string TipsToolTip {
            get {
                return ResourceManager.GetString("TipsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle fullscreen mode. (You may also use Alt+Enter on a PC.).
        /// </summary>
        public static string ToggleFullscreenTooltip {
            get {
                return ResourceManager.GetString("ToggleFullscreenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total games played:.
        /// </summary>
        public static string TotalGamesPlayed {
            get {
                return ResourceManager.GetString("TotalGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the best place to learn Go if you don&apos;t know anything at all about the game..
        /// </summary>
        public static string TutorialToolTip {
            get {
                return ResourceManager.GetString("TutorialToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Handicap.
        /// </summary>
        public static string WhiteHandicap {
            get {
                return ResourceManager.GetString("WhiteHandicap", resourceCulture);
            }
        }
    }
}
