//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaGo.UI.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmegaGo.UI.Localization.LocalizedStrings", typeof(LocalizedStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluffy uses an n-ply alpha-beta tree to figure out the best move. This is often called the minimax algorithm. In the last layer, heuristics are used to score the board position.
        ///Fluffy will always and only pass in response to its opponent passing.
        ///You may set the depth the AI will search. Increasing the depth will increase the AI&apos;s thinking time..
        /// </summary>
        public static string AI_AlphaBetaPlayerWrapper_Description {
            get {
                return ResourceManager.GetString("AI_AlphaBetaPlayerWrapper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluffy (minimax).
        /// </summary>
        public static string AI_AlphaBetaPlayerWrapper_Name {
            get {
                return ResourceManager.GetString("AI_AlphaBetaPlayerWrapper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strongest AI program in this game, the Defeatist will resign the first time it gets the chance to. You are simply not worth its time.
        ///After you make your first move, or even before that, the AI will conclude that it&apos;s much stronger than you and just resign in order to not play a game with a foregone conclusion..
        /// </summary>
        public static string AI_DefeatistAI_Description {
            get {
                return ResourceManager.GetString("AI_DefeatistAI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeatist.
        /// </summary>
        public static string AI_DefeatistAI_Name {
            get {
                return ResourceManager.GetString("AI_DefeatistAI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuego is a well-known open-source Go-playing engine written at the University of Alberta in Canada.
        ///It uses Monte Carlo tree search to make moves. It&apos;s capable of placing stones, passing and resigning, as the situation calls for.
        ///We recommend you use this AI program for all of your games..
        /// </summary>
        public static string AI_FuegoAI_Description {
            get {
                return ResourceManager.GetString("AI_FuegoAI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuego.
        /// </summary>
        public static string AI_FuegoAI_Name {
            get {
                return ResourceManager.GetString("AI_FuegoAI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AI uses a simple heuristic to determine where to play the next move. The heuristic is based on influence and on all previous stone placements in the game history.
        ///This AI will pass only in response to its opponent passing, in which case it will always pass..
        /// </summary>
        public static string AI_HeuristicPlayerWrapper_Description {
            get {
                return ResourceManager.GetString("AI_HeuristicPlayerWrapper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Puppy (heuristic).
        /// </summary>
        public static string AI_HeuristicPlayerWrapper_Name {
            get {
                return ResourceManager.GetString("AI_HeuristicPlayerWrapper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AI will select a random position at which it can play and it will play there. It will pass as soon its opponent passes..
        /// </summary>
        public static string AI_RandomAI_Description {
            get {
                return ResourceManager.GetString("AI_RandomAI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string AI_RandomAI_Name {
            get {
                return ResourceManager.GetString("AI_RandomAI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AI plays random moves while the board is not empty.
        ///I dare you to let two Fish play against each other. The game will never end (unless you&apos;re very lucky)..
        /// </summary>
        public static string AI_RandomPlayerWrapper_Description {
            get {
                return ResourceManager.GetString("AI_RandomPlayerWrapper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fish.
        /// </summary>
        public static string AI_RandomPlayerWrapper_Name {
            get {
                return ResourceManager.GetString("AI_RandomPlayerWrapper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sound effect should play:.
        /// </summary>
        public static string ASoundEffectShouldPlay {
            get {
                return ResourceManager.GetString("ASoundEffectShouldPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant AI program.
        /// </summary>
        public static string AssistantAIProgram {
            get {
                return ResourceManager.GetString("AssistantAIProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artificial intelligence.
        /// </summary>
        public static string AssistPanel {
            get {
                return ResourceManager.GetString("AssistPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string AudioPanel {
            get {
                return ResourceManager.GetString("AudioPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string AutoLanguage {
            get {
                return ResourceManager.GetString("AutoLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic orange.
        /// </summary>
        public static string BackgroundColor_Basic {
            get {
                return ResourceManager.GetString("BackgroundColor_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string BackgroundColor_Green {
            get {
                return ResourceManager.GetString("BackgroundColor_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string BackgroundColor_None {
            get {
                return ResourceManager.GetString("BackgroundColor_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bamboo forest.
        /// </summary>
        public static string BackgroundImage_Forest {
            get {
                return ResourceManager.GetString("BackgroundImage_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go board.
        /// </summary>
        public static string BackgroundImage_Go {
            get {
                return ResourceManager.GetString("BackgroundImage_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string BackgroundImage_None {
            get {
                return ResourceManager.GetString("BackgroundImage_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shinto shrine.
        /// </summary>
        public static string BackgroundImage_Shrine {
            get {
                return ResourceManager.GetString("BackgroundImage_Shrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zen temple.
        /// </summary>
        public static string BackgroundImage_Temple {
            get {
                return ResourceManager.GetString("BackgroundImage_Temple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board border thickness.
        /// </summary>
        public static string BoardBorderThickness {
            get {
                return ResourceManager.GetString("BoardBorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board settings.
        /// </summary>
        public static string BoardSettings {
            get {
                return ResourceManager.GetString("BoardSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Size.
        /// </summary>
        public static string BoardSize {
            get {
                return ResourceManager.GetString("BoardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Theme.
        /// </summary>
        public static string BoardTheme {
            get {
                return ResourceManager.GetString("BoardTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaya wood.
        /// </summary>
        public static string BoardTheme_KayaWood {
            get {
                return ResourceManager.GetString("BoardTheme_KayaWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oak wood.
        /// </summary>
        public static string BoardTheme_OakWood {
            get {
                return ResourceManager.GetString("BoardTheme_OakWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabaki.
        /// </summary>
        public static string BoardTheme_SabakiBoard {
            get {
                return ResourceManager.GetString("BoardTheme_SabakiBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid color.
        /// </summary>
        public static string BoardTheme_SolidColor {
            get {
                return ResourceManager.GetString("BoardTheme_SolidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual board.
        /// </summary>
        public static string BoardTheme_VirtualBoard {
            get {
                return ResourceManager.GetString("BoardTheme_VirtualBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell size.
        /// </summary>
        public static string CellSize {
            get {
                return ResourceManager.GetString("CellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View information about the game authors and license information..
        /// </summary>
        public static string CreditsToolTip {
            get {
                return ResourceManager.GetString("CreditsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selection.
        /// </summary>
        public static string DeleteSelection {
            get {
                return ResourceManager.GetString("DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable even in online games.
        /// </summary>
        public static string EnableEvenInOnlineGames {
            get {
                return ResourceManager.GetString("EnableEvenInOnlineGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is frowned upon to use AI assistance during games against human opponents without their knowledge..
        /// </summary>
        public static string EnableEvenInOnlineGamesTooltip {
            get {
                return ResourceManager.GetString("EnableEvenInOnlineGamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable hints.
        /// </summary>
        public static string EnableHints {
            get {
                return ResourceManager.GetString("EnableHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by source.
        /// </summary>
        public static string FilterBySource {
            get {
                return ResourceManager.GetString("FilterBySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen Mode.
        /// </summary>
        public static string FullscreenModeCheckbox {
            get {
                return ResourceManager.GetString("FullscreenModeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game library.
        /// </summary>
        public static string GameLibrary {
            get {
                return ResourceManager.GetString("GameLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library of your past games and all your SGF files.
        /// </summary>
        public static string GameLibraryToolTip {
            get {
                return ResourceManager.GetString("GameLibraryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay.
        /// </summary>
        public static string Gameplay {
            get {
                return ResourceManager.GetString("Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the rules, documentation and other interesting information..
        /// </summary>
        public static string HelpToolTip {
            get {
                return ResourceManager.GetString("HelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight illegal Ko moves.
        /// </summary>
        public static string HighlightIllegalKoMoves {
            get {
                return ResourceManager.GetString("HighlightIllegalKoMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can&apos;t place a stone on a point because it would violate the Ko rule, the point will be highlighted..
        /// </summary>
        public static string HighlightIllegalKoMovesTooltip {
            get {
                return ResourceManager.GetString("HighlightIllegalKoMovesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight last move.
        /// </summary>
        public static string HighlightLastMove {
            get {
                return ResourceManager.GetString("HighlightLastMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight recent captures.
        /// </summary>
        public static string HighlightRecentCaptures {
            get {
                return ResourceManager.GetString("HighlightRecentCaptures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a stone was captured during the previous move, its intersection will be highlighted..
        /// </summary>
        public static string HighlightRecentCapturesTooltip {
            get {
                return ResourceManager.GetString("HighlightRecentCapturesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotseat games played:.
        /// </summary>
        public static string HotseatGamesPlayed {
            get {
                return ResourceManager.GetString("HotseatGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string InputPanel {
            get {
                return ResourceManager.GetString("InputPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, restart the game to see the language you have chosen..
        /// </summary>
        public static string LanguageChangeInfo {
            get {
                return ResourceManager.GetString("LanguageChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load folder.
        /// </summary>
        public static string LoadFolder {
            get {
                return ResourceManager.GetString("LoadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local game.
        /// </summary>
        public static string LocalGame {
            get {
                return ResourceManager.GetString("LocalGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Go against another player on the same device or against an AI..
        /// </summary>
        public static string LocalGameToolTip {
            get {
                return ResourceManager.GetString("LocalGameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making a move requires a confirmation click.
        /// </summary>
        public static string MakingAMoveRequiresAConfirmationClick {
            get {
                return ResourceManager.GetString("MakingAMoveRequiresAConfirmationClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master volume.
        /// </summary>
        public static string MasterVolume {
            get {
                return ResourceManager.GetString("MasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music volume.
        /// </summary>
        public static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute all.
        /// </summary>
        public static string MuteAll {
            get {
                return ResourceManager.GetString("MuteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Go.
        /// </summary>
        public static string OmegaGo {
            get {
                return ResourceManager.GetString("OmegaGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Go rank:.
        /// </summary>
        public static string OmegaGoRankColon {
            get {
                return ResourceManager.GetString("OmegaGoRankColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-line game.
        /// </summary>
        public static string OnlineGame {
            get {
                return ResourceManager.GetString("OnlineGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online games played:.
        /// </summary>
        public static string OnlineGamesPlayed {
            get {
                return ResourceManager.GetString("OnlineGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online games won:.
        /// </summary>
        public static string OnlineGamesWon {
            get {
                return ResourceManager.GetString("OnlineGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Go against players on the IGS or OGS online servers..
        /// </summary>
        public static string OnlineGameToolTip {
            get {
                return ResourceManager.GetString("OnlineGameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        public static string PointsColon {
            get {
                return ResourceManager.GetString("PointsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests completed:.
        /// </summary>
        public static string QuestsCompleted {
            get {
                return ResourceManager.GetString("QuestsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Novice.
        /// </summary>
        public static string Rank1 {
            get {
                return ResourceManager.GetString("Rank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Apprentice.
        /// </summary>
        public static string Rank2 {
            get {
                return ResourceManager.GetString("Rank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Expert.
        /// </summary>
        public static string Rank3 {
            get {
                return ResourceManager.GetString("Rank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Master.
        /// </summary>
        public static string Rank4 {
            get {
                return ResourceManager.GetString("Rank4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Graduate.
        /// </summary>
        public static string Rank5 {
            get {
                return ResourceManager.GetString("Rank5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all progress?.
        /// </summary>
        public static string ResetAllProgress_Caption {
            get {
                return ResourceManager.GetString("ResetAllProgress_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All game counters will be reduced to zero. All points will be lost. You will have the lowest rank. Information about what tsumego problems you solved will be lost. You will keep your current in-progress quests..
        /// </summary>
        public static string ResetAllProgress_Content {
            get {
                return ResourceManager.GetString("ResetAllProgress_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ResetAllProgress_No {
            get {
                return ResourceManager.GetString("ResetAllProgress_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all progress!.
        /// </summary>
        public static string ResetAllProgress_Yes {
            get {
                return ResourceManager.GetString("ResetAllProgress_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGA.
        /// </summary>
        public static string RulesetType_AGA {
            get {
                return ResourceManager.GetString("RulesetType_AGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string RulesetType_Chinese {
            get {
                return ResourceManager.GetString("RulesetType_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string RulesetType_Japanese {
            get {
                return ResourceManager.GetString("RulesetType_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language, audio, visual style and many other things..
        /// </summary>
        public static string SettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound effects volume.
        /// </summary>
        public static string SfxVolume {
            get {
                return ResourceManager.GetString("SfxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show coordinates.
        /// </summary>
        public static string ShowCoordinates {
            get {
                return ResourceManager.GetString("ShowCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the tutorial button in main menu.
        /// </summary>
        public static string ShowTutorialButton {
            get {
                return ResourceManager.GetString("ShowTutorialButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleplayer.
        /// </summary>
        public static string Singleplayer {
            get {
                return ResourceManager.GetString("Singleplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn Go, play against an AI, solve problems or gain experience completing quests..
        /// </summary>
        public static string SingleplayerToolTip {
            get {
                return ResourceManager.GetString("SingleplayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo games played:.
        /// </summary>
        public static string SoloGamesPlayed {
            get {
                return ResourceManager.GetString("SoloGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo games won:.
        /// </summary>
        public static string SoloGamesWon {
            get {
                return ResourceManager.GetString("SoloGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your winrate and other statistics..
        /// </summary>
        public static string StatisticsToolTip {
            get {
                return ResourceManager.GetString("StatisticsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stones Theme.
        /// </summary>
        public static string StonesTheme {
            get {
                return ResourceManager.GetString("StonesTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polished stones.
        /// </summary>
        public static string StoneTheme_PolishedBitmap {
            get {
                return ResourceManager.GetString("StoneTheme_PolishedBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabaki.
        /// </summary>
        public static string StoneTheme_Sabaki {
            get {
                return ResourceManager.GetString("StoneTheme_Sabaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid color.
        /// </summary>
        public static string StoneTheme_SolidColor {
            get {
                return ResourceManager.GetString("StoneTheme_SolidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string ThemesPanel {
            get {
                return ResourceManager.GetString("ThemesPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide tips..
        /// </summary>
        public static string TipsToolTip {
            get {
                return ResourceManager.GetString("TipsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle fullscreen mode. (You may also use Alt+Enter on a PC.).
        /// </summary>
        public static string ToggleFullscreenTooltip {
            get {
                return ResourceManager.GetString("ToggleFullscreenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total games played:.
        /// </summary>
        public static string TotalGamesPlayed {
            get {
                return ResourceManager.GetString("TotalGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total games won:.
        /// </summary>
        public static string TotalGamesWon {
            get {
                return ResourceManager.GetString("TotalGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsumego problems solved:.
        /// </summary>
        public static string TsumegoProblemsSolved {
            get {
                return ResourceManager.GetString("TsumegoProblemsSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the best place to learn Go if you don&apos;t know anything at all about the game..
        /// </summary>
        public static string TutorialToolTip {
            get {
                return ResourceManager.GetString("TutorialToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When another player places a stone.
        /// </summary>
        public static string WhenAnotherPlayerPlacesAStone {
            get {
                return ResourceManager.GetString("WhenAnotherPlayerPlacesAStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I place a stone.
        /// </summary>
        public static string WhenIPlaceAStone {
            get {
                return ResourceManager.GetString("WhenIPlaceAStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I receive a notification.
        /// </summary>
        public static string WhenIReceiveANotification {
            get {
                return ResourceManager.GetString("WhenIReceiveANotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Handicap.
        /// </summary>
        public static string WhiteHandicap {
            get {
                return ResourceManager.GetString("WhiteHandicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have advanced to a new omegaGo rank: {0}. Congratulations!.
        /// </summary>
        public static string YouHaveAdvancedToNewRankX {
            get {
                return ResourceManager.GetString("YouHaveAdvancedToNewRankX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} points (now you have {1}).
        /// </summary>
        public static string YouHaveGainedXPointsNowYouHaveY {
            get {
                return ResourceManager.GetString("YouHaveGainedXPointsNowYouHaveY", resourceCulture);
            }
        }
    }
}
